laptops= [
    {
        id: 1,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 200,
        foto: "laptop1.webp",
    },
    {
        id: 2,
        marca: "Asus",
        modelo: "Zenbook 14",
        precio: 300,
        foto: "laptop2.webp",
    },
    {
        id: 3,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop3.webp",
    },
    {
        id: 4,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop4.webp",
    },
    {
        id: 5,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop5.webp",
    },
    {
        id: 6,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop6.jpg",
    },
    {
        id: 7,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop7.jpg",
    },
    {
        id: 8,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop8.jpg",
    },
    {
        id: 9,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop9.jpg",
    }
]

telefonos= [
    {
        id : 10,
        marca: "google",
        modelo: "pixel 7",
        precio: 1000,
        foto:"google_pixel_7.jpg",
    },
    {
        id : 11,
        marca: "iphonee",
        modelo: "iphone 16",
        precio: 1500,
        foto:"jaifon.jpg",
    },
    {
        id : 12,
        marca: "Samsung ",
        modelo: "Galaxy S25ultra",
        precio: 1200,
        foto:"samsung.jpg",
    },
    {
        id: 13,
        marca: "Samsung ",
        modelo: "Galaxy A06",
        precio: 1350,
        foto:"samsung123.jpg",
    },
    {
        id: 14,
        marca: "Samsung ",
        modelo: "Galaxy A56",
        precio: 2000,
        foto:"samsungA56.jpg",
    },
    {
        id: 15,
        marca: "motorola",
        modelo: "edge",
        precio: 2000,
        foto:"motorola.jpg",
    },
    {
        id: 16,
        marca: "xiaomi",
        modelo: "A13",
        precio: 200,
        foto:"xiaomi.jpg",
    },
    {
        id: 17,
        marca: "samsumg",
        modelo: "A13",
        precio: 2100,
        foto:"samsung.jpg",
    },
    {
        id: 18,
        marca: "infinix",
        modelo: "hot50",
        precio: 2200,
        foto:"hot50.jpg",
    },
    {
        id: 19,
        marca: "infinix",
        modelo: "note40 4G",
        precio: 2300,
        foto:"note40.jpg",
    }
]

tablets= [
    {
        id : 20,
        marca: "google",
        modelo: "pixel 7",
        precio: 1000,
        foto:"google_pixel_7.jpg",
    },
    {
        id : 21,
        marca: "iphonee",
        modelo: "iphone 16",
        precio: 1500,
        foto:"jaifon.jpg",
    },
    {
        id : 22,
        marca: "Samsung ",
        modelo: "Galaxy S25ultra",
        precio: 1200,
        foto:"samsung.jpg",
    },
    {
        id: 23,
        marca: "Samsung ",
        modelo: "Galaxy A06",
        precio: 1350,
        foto:"samsung123.jpg",
    },
    {
        id: 24,
        marca: "Samsung ",
        modelo: "Galaxy A56",
        precio: 2000,
        foto:"samsungA56.jpg",
    },
    {
        id: 25,
        marca: "motorola",
        modelo: "edge",
        precio: 2000,
        foto:"motorola.jpg",
    },
    {
        id: 26,
        marca: "xiaomi",
        modelo: "A13",
        precio: 200,
        foto:"xiaomi.jpg",
    },
    {
        id: 27,
        marca: "samsumg",
        modelo: "A13",
        precio: 2100,
        foto:"samsung.jpg",
    },
    {
        id: 28,
        marca: "infinix",
        modelo: "hot50",
        precio: 2200,
        foto:"hot50.jpg",
    },
    {
        id: 29,
        marca: "infinix",
        modelo: "note40 4G",
        precio: 2300,
        foto:"note40.jpg",
    }
]