laptops= [
    {
        id: 1,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 200,
        foto: "img/laptops/laptop1.webp",
    },
    {
        id: 2,
        marca: "Asus",
        modelo: "Zenbook 14",
        precio: 300,
        foto: "img/laptops/laptop2.webp",
    },
    {
        id: 3,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop3.webp",
    },
    {
        id: 4,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop4.webp",
    },
    {
        id: 5,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop5.webp",
    },
    {
        id: 6,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop6.jpg",
    },
    {
        id: 7,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop7.jpg",
    },
    {
        id: 8,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop8.jpg",
    },
    {
        id: 9,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "img/laptops/laptop9.jpg",
    }
]

telefonos= [
    {
        id : 10,
        marca: "Google",
        modelo: "Pixel 7",
        precio: 1000,
        foto:"img/telefonos/googlepixel.jpeg",
    },
    {
        id : 11,
        marca: "Iphone",
        modelo: "Iphone 16",
        precio: 1500,
        foto:"img/telefonos/hot50.jpeg",
    },
    {
        id : 12,
        marca: "Samsung ",
        modelo: "Galaxy S25ultra",
        precio: 1200,
        foto:"img/telefonos/jaifon.jpeg",
    },
    {
        id: 13,
        marca: "Samsung ",
        modelo: "Galaxy A06",
        precio: 1350,
        foto:"img/telefonos/motorola.jpeg",
    },
    {
        id: 14,
        marca: "Samsung ",
        modelo: "Galaxy A56",
        precio: 2000,
        foto:"img/telefonos/nota40.jpeg",
    },
    {
        id: 15,
        marca: "Motorola",
        modelo: "Edge",
        precio: 2000,
        foto:"img/telefonos/samsung.jpeg",
    },
    {
        id: 16,
        marca: "Xiaomi",
        modelo: "A13",
        precio: 200,
        foto:"img/telefonos/samsung123.jpeg",
    },
    {
        id: 17,
        marca: "Samsumg",
        modelo: "A13",
        precio: 2100,
        foto:"img/telefonos/samsunga56.jpeg",
    },
    {
        id: 18,
        marca: "Infinix",
        modelo: "Hot50",
        precio: 2200,
        foto:"img/telefonos/smart.jpeg",
    },
    {
        id: 19,
        marca: "Infinix",
        modelo: "Note40 4G",
        precio: 2300,
        foto:"img/telefonos/xiaomi.jpeg",
    }
]

tablets= [
    {
        id : 20,
        marca: "Air",
        modelo: "1",
        precio: 1000,
        foto:"img/tables/Air1.jpeg",
    },
    {
        id : 21,
        marca: "Ipad",
        modelo: "8",
        precio: 1500,
        foto:"img/tables/ipad8.jpeg",
    },
    {
        id : 22,
        marca: "Ipad",
        modelo: "mini4",
        precio: 1200,
        foto:"img/tables/mini4.jpeg",
    },
    {
        id: 23,
        marca: "Ipad",
        modelo: "mini7",
        precio: 1350,
        foto:"img/tables/mini7.jpeg",
    },
    {
        id: 24,
        marca: "Ipad",
        modelo: "pro",
        precio: 2000,
        foto:"img/tables/pro.jpeg",
    },
    {
        id: 25,
        marca: "Ipad",
        modelo: "Pro",
        precio: 2000,
        foto:"img/tables/prop.jpeg",
    },
    {
        id: 26,
        marca: "Ipad",
        modelo: "tab3",
        precio: 200,
        foto:"img/tables/tab3.jpeg",
    },
    {
        id: 27,
        marca: "Ipad",
        modelo: "tab8",
        precio: 2100,
        foto:"img/tables/tabs8.jpeg",
    },
    {
        id: 28,
        marca: "Ipad",
        modelo: "X pro",
        precio: 2200,
        foto:"img/tables/xpro.jpeg",
    },

]

productos= [
    {
    id: 1,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 200,
    foto: "img/laptops/laptop1.webp",
},
{
    id: 2,
    marca: "Asus",
    modelo: "Zenbook 14",
    precio: 300,
    foto: "img/laptops/laptop2.webp",
},
{
    id: 3,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop3.webp",
},
{
    id: 4,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop4.webp",
},
{
    id: 5,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop5.webp",
},
{
    id: 6,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop6.jpg",
},
{
    id: 7,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop7.jpg",
},
{
    id: 8,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop8.jpg",
},
{
    id: 9,
    marca: "Samsung",
    modelo: "Notebook 9 Pro",
    precio: 20000,
    foto: "img/laptops/laptop9.jpg",
},
{
    id : 10,
    marca: "Google",
    modelo: "Pixel 7",
    precio: 1000,
    foto:"img/telefonos/googlepixel.jpeg",
},
{
    id : 11,
    marca: "Iphone",
    modelo: "Iphone 16",
    precio: 1500,
    foto:"img/telefonos/hot50.jpeg",
},
{
    id : 12,
    marca: "Samsung ",
    modelo: "Galaxy S25ultra",
    precio: 1200,
    foto:"img/telefonos/jaifon.jpeg",
},
{
    id: 13,
    marca: "Samsung ",
    modelo: "Galaxy A06",
    precio: 1350,
    foto:"img/telefonos/motorola.jpeg",
},
{
    id: 14,
    marca: "Samsung ",
    modelo: "Galaxy A56",
    precio: 2000,
    foto:"img/telefonos/nota40.jpeg",
},
{
    id: 15,
    marca: "Motorola",
    modelo: "Edge",
    precio: 2000,
    foto:"img/telefonos/samsung.jpeg",
},
{
    id: 16,
    marca: "Xiaomi",
    modelo: "A13",
    precio: 200,
    foto:"img/telefonos/samsung123.jpeg",
},
{
    id: 17,
    marca: "Samsumg",
    modelo: "A13",
    precio: 2100,
    foto:"img/telefonos/samsunga56.jpeg",
},
{
    id: 18,
    marca: "Infinix",
    modelo: "Hot50",
    precio: 2200,
    foto:"img/telefonos/smart.jpeg",
},
{
    id: 19,
    marca: "Infinix",
    modelo: "Note40 4G",
    precio: 2300,
    foto:"img/telefonos/xiaomi.jpeg",
},
{
    id : 20,
    marca: "Air",
    modelo: "1",
    precio: 1000,
    foto:"img/tables/Air1.jpeg",
},
{
    id : 21,
    marca: "Ipad",
    modelo: "8",
    precio: 1500,
    foto:"img/tables/ipad8.jpeg",
},
{
    id : 22,
    marca: "Ipad",
    modelo: "mini4",
    precio: 1200,
    foto:"img/tables/mini4.jpeg",
},
{
    id: 23,
    marca: "Ipad",
    modelo: "mini7",
    precio: 1350,
    foto:"img/tables/mini7.jpeg",
},
{
    id: 24,
    marca: "Ipad",
    modelo: "pro",
    precio: 2000,
    foto:"img/tables/pro.jpeg",
},
{
    id: 25,
    marca: "Ipad",
    modelo: "Pro",
    precio: 2000,
    foto:"img/tables/prop.jpeg",
},
{
    id: 26,
    marca: "Ipad",
    modelo: "tab3",
    precio: 200,
    foto:"img/tables/tab3.jpeg",
},
{
    id: 27,
    marca: "Ipad",
    modelo: "tab8",
    precio: 2100,
    foto:"img/tables/tabs8.jpeg",
},
{
    id: 28,
    marca: "Ipad",
    modelo: "X pro",
    precio: 2200,
    foto:"img/tables/xpro.jpeg",
},
]