laptops= [
    {
        id: 1,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 200,
        foto: "laptop1.webp",
    },
    {
        id: 2,
        marca: "Asus",
        modelo: "Zenbook 14",
        precio: 300,
        foto: "laptop1.webp",
    },
    {
        id: 3,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop1.webp",
    },
    {
        id: 4,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop1.webp",
    }
]

telefonos= [
    {
        id : 10,
        marca: "google",
        modelo: "pixel 7",
        precio: 1000,
        foto:"google_pixel_7.jpg",
    },
    {
        id : 11,
        marca: "iphonee",
        modelo: "iphone 16",
        precio: 1500,
        foto:"jaifon.jpg",
    },
    {
        id : 12,
        marca: "Samsung ",
        modelo: "Galaxy S25ultra",
        precio: 1200,
        foto:"samsung.jpg",
    },
    {
        id: 13,
        marca: "Samsung ",
        modelo: "Galaxy A06",
        precio: 1350,
        foto:"samsung123.jpg",
    },
    {
        id: 14,
        marca: "Samsung ",
        modelo: "Galaxy A56",
        precio: 2000,
        foto:"samsungA56.jpg",
    },
    {
        id: 15,
        marca: "motorola",
        modelo: "edge",
        precio: 2000,
        foto:"motorola.jpg",
    },
    {
        id: 16,
        marca: "xiaomi",
        modelo: "A13",
        precio: 200,
        foto:"xiaomi.jpg",
    },
    {
        id: 17,
        marca: "samsumg",
        modelo: "A13",
        precio: 2100,
        foto:"samsung.jpg",
    },
    {
        id: 18,
        marca: "infinix",
        modelo: "hot50",
        precio: 2200,
        foto:"hot50.jpg",
    },
    {
        id: 19,
        marca: "infinix",
        modelo: "note40 4G",
        precio: 2300,
        foto:"note40.jpg",
    },
    {
        id: 20,
        marca: "infinix",
        modelo: "smart 9",
        precio: 1000,
        foto:"smart9.jpg",
        }
]

tablest= [
    {
        id : 21,
        marca: "samsumg",
        modelo: "tab 3",
        precio: 850,
        foto:"tab3.jpg",
    },
    {
        id : 22,
        marca: "samsumg",
        modelo: "tabs8",
        precio: 900,
        foto:"tabs8.jpg",
    },
    {
        id : 23,
        marca: "ipad",
        modelo: "pro 2022",
        precio: 1900,
        foto:"pro.jpg",
    },
    {
        id: 24,
        marca: "ipad",
        modelo: "pro 2020",
        precio: 1400,
        foto:"prop.jpg",
    },
    {
        id: 25,
        marca: "ipad",
        modelo: "X pro",
        precio: 2100,
        foto:"xpro.jpg",
    },
    {
        id: 26,
        marca: "ipad",
        modelo: "mini 7",
        precio: 1800,
        foto:"mini 7.jpg",
    },
    {
        id: 27,
        marca: "ipad",
        modelo: "mini 4",
        precio: 250,
        foto:"mini 4.jpg",
    },
    {
        id: 28,
        marca: "ipad",
        modelo: "Air 1",
        precio: 650,
        foto:"Air 1.jpg",
    },
    {
        id: 29,
        marca: "ipad",
        modelo: "mini 8",
        precio: 1650,
        foto:"ipad 8.jpg",
    },
]