laptops= [
    {
        id: 1,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 200,
        foto: "laptop1.webp",
    },
    {
        id: 2,
        marca: "Asus",
        modelo: "Zenbook 14",
        precio: 300,
        foto: "laptop2.webp",
    },
    {
        id: 3,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop3.webp",
    },
    {
        id: 4,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop4.webp",
    },
    {
        id: 5,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop5.webp",
    },
    {
        id: 6,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop6.jpg",
    },
    {
        id: 7,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop7.jpg",
    },
    {
        id: 8,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop8.jpg",
    },
    {
        id: 9,
        marca: "Samsung",
        modelo: "Notebook 9 Pro",
        precio: 20000,
        foto: "laptop9.jpg",
    }
]